// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Badge': string;
  'Badge__medium': string;
  'Badge__small': string;
}
export const cssExports: CssExports;
export default cssExports;
